Repository mash-up-kr/Dionysos-iOS, pull requests merged in 2020-07, with the labels that each got.

#15 ✨ 네트워크 레이어 구현
  Dionysos.xcodeproj/project.pbxproj
  Dionysos/.swiftlint.yml
  Dionysos/AppDelegate.swift
  Dionysos/Common/Logger.swift
  Dionysos/Common/SocialLogin/AppleLogin.swift
  Dionysos/Common/SocialLogin/FacebookLogin.swift
  Dionysos/Common/SocialLogin/KakaoLogin.swift
  Dionysos/Common/SocialLoginHelper.swift
  Dionysos/Main/ViewController.swift
  Dionysos/Network/DionysosProvider.swift
  Dionysos/Network/DionysosService.swift
  Dionysos/Network/DionysosTarget.swift
  Dionysos/Network/NetworkProvider.swift
Labels: 🔨 기능 개발, 🙋🏻‍♀️ 리뷰 요청

#16 애플 로그인
  Dionysos.xcodeproj/project.pbxproj
  Dionysos/Dionysos.entitlements
  Dionysos/Main/ViewController.swift
Labels: 🙋🏻‍♀️ 리뷰 요청

#23 add keyboardConstraintHandler
  Dionysos.xcodeproj/project.pbxproj
  Dionysos/Common/KeyboardConstraintHandler.swift
  Dionysos/Info.plist
  Dionysos/Main/Base.lproj/Main.storyboard
  Dionysos/SignUp/NicknameInputViewController.swift
  Dionysos/SignUp/SignUp.storyboard
Labels: 🙋🏻‍♀️ 리뷰 요청

#27 ⏳ 타이머 구현
  Dionysos.xcodeproj/project.pbxproj
  Dionysos/Common/SocialLogin/AppleLogin.swift
  Dionysos/Common/SocialLogin/FacebookLogin.swift
  Dionysos/Common/Timer/MGKTimer.swift
  Dionysos/Common/Timer/TimeAmount.swift
  Dionysos/Common/Timer/TimeTask.swift
Labels: 🔨 기능 개발, 🙋🏻‍♀️ 리뷰 요청

#30 ✨feat: Custom Alert Controller 구현
  Dionysos.xcodeproj/project.pbxproj
  Dionysos/Alert/MGKAlert.storyboard
  Dionysos/Alert/MGKAlertViewController.swift
  Dionysos/Colors.xcassets/Contents.json
  Dionysos/Colors.xcassets/transparentBlack.colorset/Contents.json
Labels: 🔨 기능 개발, 🙋🏻‍♀️ 리뷰 요청

#32 좋버그있는 QuestionView
  Dionysos.xcodeproj/project.pbxproj
  Dionysos/Alert/MGKAlert.storyboard
  Dionysos/Alert/MGKAlertViewController.swift
  Dionysos/Main/Home/Base.lproj/Main.storyboard
  Dionysos/Main/Home/MainViewController.swift
  Dionysos/SignUp/SignInViewController.swift
  Dionysos/View/Question/QuestionView.swift
  Dionysos/View/Question/QuestionView.xib
Labels: 🔨 기능 개발, 🙋🏻‍♀️ 리뷰 요청

#34 ✨feat: Facebook Auth 구현
  Dionysos.xcodeproj/project.pbxproj
  Dionysos/Common/SocialLogin/FacebookAuth.swift
  Dionysos/SignUp/SignInViewController.swift
Labels: 🔨 기능 개발
